FoodSchema:
  ingredient:
    type: str
    description: "Name of the ingredient"
  quantity:
    type: float
    description: "Quantity of the ingredient"
  process:
    type: Optional[str]
    description: "Process of the ingredient eg., chopped, sliced, etc."


#give me a sample for the schema in json format






